### ISSUE TITLE
APPLY called with literal list argument

### ISSUE THREAD

**Issue by phoe** [AccelerationNet/access#10]
https://github.com/AccelerationNet/access/blob/8a8259e5c93605e9c68cc697efee71d09d6fc873/access.lisp#L492-L498

`(apply '(setf aref) ...)` is likely non-conforming CL because lists are not funcallable. In other words, a list is not a function designator, and `apply` accepts only function designators (as opposed to extended function designators, which are allowed to be lists).

We probably want `(apply #'(setf aref) ...)` instead.

**Comment by phoe** [comment]
More: `#'(setf aref)` needs not even exist, and is therefore also non-portable.

[CLHS 5.1.1.2](http://www.lispworks.com/documentation/HyperSpec/Body/05_aab.htm) states:

>  For each standardized accessor function F, unless it is explicitly documented otherwise, it is implementation-dependent whether the ability to use an F form as a setf place is implemented by a setf expander or a setf function. Also, it follows from this that it is implementation-dependent whether the name (setf F) is fbound. 

Using `setf apply` should be considered instead, as per [CLHS 5.1.2.5](http://www.lispworks.com/documentation/HyperSpec/Body/05_abe.htm).

**Comment by bobbysmith007** [comment]
Thank you, I dont do very much lisp at all for the past couple years.  I appreciate you assistance

**Comment by phoe** [comment]
No problem - thank you for the merge.
