### ISSUE TITLE
compilation problem on SBCL 1.2.14

### ISSUE THREAD

**Issue by macdavid313** [AccelerationNet/access#6]
; in: DEFINE-SETF-EXPANDER ACCESS
;     (DEFINE-SETF-EXPANDER ACCESS:ACCESS
;                           (ACCESS::PLACE ACCESS::K
;                            &KEY TYPE ACCESS::TEST ACCESS::KEY &ENVIRONMENT
;                            ACCESS::ENV
;                            &AUX (ACCESS::NEW-VAL (GENSYM "NEW-VAL"))
;                            (ACCESS::PLACE-STORE (GENSYM "PLACE")))
;       "This should allow setting places through access"
;       (DECLARE (IGNORE ACCESS::ENV))
;       (VALUES NIL NIL `(,ACCESS::NEW-VAL)
;               `(PROGN
;                 (MULTIPLE-VALUE-BIND (,ACCESS::NEW-VAL ,ACCESS::PLACE-STORE)
;                     (ACCESS:SET-ACCESS ,ACCESS::NEW-VAL ,ACCESS::PLACE ,ACCESS::K
;                      :TEST ,ACCESS::TEST :TYPE ,TYPE :KEY ,ACCESS::KEY)
;                   (SETF #)
;                   ,ACCESS::NEW-VAL))
;               `(ACCESS:ACCESS ,ACCESS::PLACE ,ACCESS::K :TEST ,ACCESS::TEST :TYPE
;                 ,TYPE :KEY ,ACCESS::KEY)))
; 
; caught ERROR:
;   (during macroexpansion of (DEFINE-SETF-EXPANDER ACCESS ...))
;   misplaced &AUX in lambda list: (PLACE K &KEY TYPE TEST KEY &ENVIRONMENT ENV
;                                   &AUX (NEW-VAL (GENSYM "NEW-VAL"))
;                                   (PLACE-STORE (GENSYM "PLACE")))

**Comment by bobbysmith007** [comment]
This was (should have been) fixed in https://github.com/AccelerationNet/access/commit/799b84836b67370ded6ac4a7fbeadc43cc14f4fc

Thanks for the bug report.  If you happen to be running with this patch and still get the errors, please let me know.

Cheers,
Russ
